language: java
jdk:
  - openjdk8
script: ./gradlew clean compileJava compileTestJava test
install: true
notifications:
  email:
    recipients:
      - "dmulloy2@live.com"
    on_success: change
    on_failure: always
